name: Deploy to Render

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out your repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username secret
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password/token secret

      # Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest

      # Deploy to Render via Render's API
      - name: Deploy to Render
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"  # Render API key secret
            -H "Content-Type: application/json" \
            -d '{
              "serviceId": "${{ secrets.RENDER_SERVICE_ID }}",  # Render service ID secret
              "clearCache": true
            }' \
            https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys
