name: Deploy to Render

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out your repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.ekta100 }}  # Your Docker Hub username secret
          password: ${{ secrets.Ekta12345678 }}  # Your Docker Hub password or token secret

      # Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.ekta100 }}/my-app:latest .
          docker push ${{ secrets.ekta100 }}/my-app:latest

      # Deploy to Render via Render's API
      - name: Deploy to Render
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.rnd_GUjnnvTX14JyDLd5x3iE4DHwxBam }}"  # Your Render API token secret
            -H "Content-Type: application/json" \
            -d '{
              "serviceId": "srv-ctlahm0gph6c739jiv5g",  # Replace with your actual Render service ID
              "clearCache": true
            }' \
            https://api.render.com/v1/services/srv-ctlahm0gph6c739jiv5g/deploys  # Replace with your actual service ID
